server:
  port: 8080
dubbo:
  application:
    name: provider-ticket
  #配置注册中心，用来发布服务 zk
  registry:
    address: zookeeper://81.70.223.139:2181
  protocol:
    port: 12398   #20800 zk内部代理服务端口
  #扫描业务目录
  scan:
    base-packages: com.weichuang.ticket.service